[package]
name = "whir-ivc"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
whir-core = { path = "../whir-core", default-features = false }
whir-pcs = { path = "../whir-pcs", default-features = false }
whir-spartan = { path = "../whir-spartan", default-features = false }
accumulation = { path = "../accumulation", default-features = false }
warp = { path = "../warp", default-features = false }
whir-circuit = { path = "../whir-circuit", default-features = false }
whir-cp-snark = { path = "../whir-cp-snark", default-features = false, optional = true }

p3-field.workspace = true
p3-challenger.workspace = true
p3-commit.workspace = true
p3-dft.workspace = true
p3-matrix.workspace = true
p3-maybe-rayon.workspace = true
p3-merkle-tree.workspace = true
p3-symmetric.workspace = true
p3-koala-bear.workspace = true
p3-poseidon2.workspace = true
p3-mds.workspace = true

serde.workspace = true
rayon = { workspace = true, optional = true }
tracing.workspace = true
rand.workspace = true

[dev-dependencies]
p3-keccak.workspace = true
rand = { workspace = true, features = ["std", "std_rng", "thread_rng"] }

[features]
default = ["parallel"]
parallel = ["dep:rayon", "p3-maybe-rayon/parallel", "whir-core/parallel", "whir-pcs/parallel", "whir-spartan/parallel", "accumulation/parallel", "warp/parallel", "whir-circuit/parallel"]
bench-timing = ["whir-pcs/bench-timing"]
symphony = ["dep:whir-cp-snark"]

[lints]
workspace = true
