[package]
name = "whir-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
p3-field.workspace = true
p3-matrix.workspace = true
p3-util.workspace = true
p3-maybe-rayon.workspace = true
p3-multilinear-util.workspace = true

serde.workspace = true
rayon = { workspace = true, optional = true }
itertools.workspace = true
libm.workspace = true
thiserror.workspace = true
tracing.workspace = true
rand.workspace = true

[features]
default = ["parallel"]
parallel = ["dep:rayon", "p3-maybe-rayon/parallel", "p3-util/parallel"]

[dev-dependencies]
p3-koala-bear.workspace = true
p3-goldilocks.workspace = true
proptest.workspace = true
rand = { workspace = true, features = ["std", "std_rng", "thread_rng"] }

[lints]
workspace = true
